Mon:
  enableMsg: false
  # msg: " "
  classCnt: 10
  classes:
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
Tue:
  enableMsg: false
  # msg: " "
  classCnt: 10
  classes:
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
Wed:
  enableMsg: false
  # msg: " "
  classCnt: 10
  classes:
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
Thu:
  enableMsg: false
  # msg: " "
  classCnt: 10
  classes:
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
Fri:
  enableMsg: false
  # msg: " "
  classCnt: 10
  classes:
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
    - name: " "
      startTime: " "
      meetingID: " "
      passwordProtected: false
    # password: " "
Sat:
  #  enableMsg: true
  #  msg: "It's Saturday, why are you here?"
  classCnt: 10
  classes:
    - name: "test"
      startTime: "13:05"
      meetingID: "880 096 5369"
      autoJoin: true
      passwordProtected: false
Sun:
  enableMsg: true
  msg: "It's Sunday, why are you here?"
